services:
  a03-injection-csrf:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"   
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
